/**
 * Every country, its calling code, and its national significant-number
 * length(s) (digits dialled *after* the country code) — used to validate
 * the phone field per-country instead of one generic "7+ digits" rule.
 *
 * Numbering plans aren't all fixed-length in reality (several countries
 * accept a short range depending on number type); where that's the case we
 * list every length that's actually in common use. India's is a single
 * fixed 10, per the assignment's requirement.
 */

export interface Country {
  name: string;
  iso2: string;
  dial: string;
  /** Expected digit count(s) of the number *after* the dial code. */
  lengths: number[];
}

function country(name: string, iso2: string, dial: string, lengths: number | number[]): Country {
  return { name, iso2, dial, lengths: Array.isArray(lengths) ? lengths : [lengths] };
}

export const COUNTRIES: Country[] = [
  country("India", "IN", "+91", 10),
  country("United States", "US", "+1", 10),
  country("Canada", "CA", "+1", 10),
  country("United Kingdom", "GB", "+44", 10),
  country("Afghanistan", "AF", "+93", 9),
  country("Albania", "AL", "+355", [8, 9]),
  country("Algeria", "DZ", "+213", 9),
  country("Andorra", "AD", "+376", 6),
  country("Angola", "AO", "+244", 9),
  country("Argentina", "AR", "+54", 10),
  country("Armenia", "AM", "+374", 8),
  country("Australia", "AU", "+61", 9),
  country("Austria", "AT", "+43", [10, 11]),
  country("Azerbaijan", "AZ", "+994", 9),
  country("Bahamas", "BS", "+1", 10),
  country("Bahrain", "BH", "+973", 8),
  country("Bangladesh", "BD", "+880", 10),
  country("Barbados", "BB", "+1", 10),
  country("Belarus", "BY", "+375", 9),
  country("Belgium", "BE", "+32", 9),
  country("Belize", "BZ", "+501", 7),
  country("Benin", "BJ", "+229", 8),
  country("Bhutan", "BT", "+975", 8),
  country("Bolivia", "BO", "+591", 8),
  country("Bosnia and Herzegovina", "BA", "+387", 8),
  country("Botswana", "BW", "+267", 8),
  country("Brazil", "BR", "+55", 11),
  country("Brunei", "BN", "+673", 7),
  country("Bulgaria", "BG", "+359", 9),
  country("Burkina Faso", "BF", "+226", 8),
  country("Burundi", "BI", "+257", 8),
  country("Cambodia", "KH", "+855", 9),
  country("Cameroon", "CM", "+237", 9),
  country("Cape Verde", "CV", "+238", 7),
  country("Central African Republic", "CF", "+236", 8),
  country("Chad", "TD", "+235", 8),
  country("Chile", "CL", "+56", 9),
  country("China", "CN", "+86", 11),
  country("Colombia", "CO", "+57", 10),
  country("Comoros", "KM", "+269", 7),
  country("Congo (DRC)", "CD", "+243", 9),
  country("Congo (Republic)", "CG", "+242", 9),
  country("Costa Rica", "CR", "+506", 8),
  country("Croatia", "HR", "+385", 9),
  country("Cuba", "CU", "+53", 8),
  country("Cyprus", "CY", "+357", 8),
  country("Czechia", "CZ", "+420", 9),
  country("Denmark", "DK", "+45", 8),
  country("Djibouti", "DJ", "+253", 8),
  country("Dominican Republic", "DO", "+1", 10),
  country("East Timor", "TL", "+670", 8),
  country("Ecuador", "EC", "+593", 9),
  country("Egypt", "EG", "+20", 10),
  country("El Salvador", "SV", "+503", 8),
  country("Equatorial Guinea", "GQ", "+240", 9),
  country("Eritrea", "ER", "+291", 7),
  country("Estonia", "EE", "+372", 8),
  country("Eswatini", "SZ", "+268", 8),
  country("Ethiopia", "ET", "+251", 9),
  country("Fiji", "FJ", "+679", 7),
  country("Finland", "FI", "+358", [9, 10]),
  country("France", "FR", "+33", 9),
  country("Gabon", "GA", "+241", 8),
  country("Gambia", "GM", "+220", 7),
  country("Georgia", "GE", "+995", 9),
  country("Germany", "DE", "+49", [10, 11]),
  country("Ghana", "GH", "+233", 9),
  country("Greece", "GR", "+30", 10),
  country("Grenada", "GD", "+1", 10),
  country("Guatemala", "GT", "+502", 8),
  country("Guinea", "GN", "+224", 9),
  country("Guinea-Bissau", "GW", "+245", 7),
  country("Guyana", "GY", "+592", 7),
  country("Haiti", "HT", "+509", 8),
  country("Honduras", "HN", "+504", 8),
  country("Hong Kong", "HK", "+852", 8),
  country("Hungary", "HU", "+36", 9),
  country("Iceland", "IS", "+354", 7),
  country("Indonesia", "ID", "+62", [9, 10, 11]),
  country("Iran", "IR", "+98", 10),
  country("Iraq", "IQ", "+964", 10),
  country("Ireland", "IE", "+353", 9),
  country("Israel", "IL", "+972", 9),
  country("Italy", "IT", "+39", 10),
  country("Ivory Coast", "CI", "+225", 10),
  country("Jamaica", "JM", "+1", 10),
  country("Japan", "JP", "+81", 10),
  country("Jordan", "JO", "+962", 9),
  country("Kazakhstan", "KZ", "+7", 10),
  country("Kenya", "KE", "+254", 9),
  country("Kiribati", "KI", "+686", 8),
  country("Kosovo", "XK", "+383", 8),
  country("Kuwait", "KW", "+965", 8),
  country("Kyrgyzstan", "KG", "+996", 9),
  country("Laos", "LA", "+856", 10),
  country("Latvia", "LV", "+371", 8),
  country("Lebanon", "LB", "+961", [7, 8]),
  country("Lesotho", "LS", "+266", 8),
  country("Liberia", "LR", "+231", [7, 8]),
  country("Libya", "LY", "+218", 9),
  country("Liechtenstein", "LI", "+423", 7),
  country("Lithuania", "LT", "+370", 8),
  country("Luxembourg", "LU", "+352", 9),
  country("Macau", "MO", "+853", 8),
  country("Madagascar", "MG", "+261", 9),
  country("Malawi", "MW", "+265", 9),
  country("Malaysia", "MY", "+60", [9, 10]),
  country("Maldives", "MV", "+960", 7),
  country("Mali", "ML", "+223", 8),
  country("Malta", "MT", "+356", 8),
  country("Marshall Islands", "MH", "+692", 7),
  country("Mauritania", "MR", "+222", 8),
  country("Mauritius", "MU", "+230", 7),
  country("Mexico", "MX", "+52", 10),
  country("Micronesia", "FM", "+691", 7),
  country("Moldova", "MD", "+373", 8),
  country("Monaco", "MC", "+377", 8),
  country("Mongolia", "MN", "+976", 8),
  country("Montenegro", "ME", "+382", 8),
  country("Morocco", "MA", "+212", 9),
  country("Mozambique", "MZ", "+258", 9),
  country("Myanmar", "MM", "+95", [8, 9, 10]),
  country("Namibia", "NA", "+264", 9),
  country("Nauru", "NR", "+674", 7),
  country("Nepal", "NP", "+977", 10),
  country("Netherlands", "NL", "+31", 9),
  country("New Zealand", "NZ", "+64", [8, 9]),
  country("Nicaragua", "NI", "+505", 8),
  country("Niger", "NE", "+227", 8),
  country("Nigeria", "NG", "+234", 10),
  country("North Korea", "KP", "+850", 10),
  country("North Macedonia", "MK", "+389", 8),
  country("Norway", "NO", "+47", 8),
  country("Oman", "OM", "+968", 8),
  country("Pakistan", "PK", "+92", 10),
  country("Palau", "PW", "+680", 7),
  country("Palestine", "PS", "+970", 9),
  country("Panama", "PA", "+507", 8),
  country("Papua New Guinea", "PG", "+675", 8),
  country("Paraguay", "PY", "+595", 9),
  country("Peru", "PE", "+51", 9),
  country("Philippines", "PH", "+63", 10),
  country("Poland", "PL", "+48", 9),
  country("Portugal", "PT", "+351", 9),
  country("Qatar", "QA", "+974", 8),
  country("Romania", "RO", "+40", 9),
  country("Russia", "RU", "+7", 10),
  country("Rwanda", "RW", "+250", 9),
  country("Saint Lucia", "LC", "+1", 10),
  country("Samoa", "WS", "+685", [5, 6, 7]),
  country("San Marino", "SM", "+378", [6, 10]),
  country("Saudi Arabia", "SA", "+966", 9),
  country("Senegal", "SN", "+221", 9),
  country("Serbia", "RS", "+381", [8, 9]),
  country("Seychelles", "SC", "+248", 7),
  country("Sierra Leone", "SL", "+232", 8),
  country("Singapore", "SG", "+65", 8),
  country("Slovakia", "SK", "+421", 9),
  country("Slovenia", "SI", "+386", 8),
  country("Solomon Islands", "SB", "+677", 7),
  country("Somalia", "SO", "+252", [7, 8]),
  country("South Africa", "ZA", "+27", 9),
  country("South Korea", "KR", "+82", [9, 10]),
  country("South Sudan", "SS", "+211", 9),
  country("Spain", "ES", "+34", 9),
  country("Sri Lanka", "LK", "+94", 9),
  country("Sudan", "SD", "+249", 9),
  country("Suriname", "SR", "+597", 7),
  country("Sweden", "SE", "+46", 9),
  country("Switzerland", "CH", "+41", 9),
  country("Syria", "SY", "+963", 9),
  country("Taiwan", "TW", "+886", 9),
  country("Tajikistan", "TJ", "+992", 9),
  country("Tanzania", "TZ", "+255", 9),
  country("Thailand", "TH", "+66", 9),
  country("Togo", "TG", "+228", 8),
  country("Tonga", "TO", "+676", [5, 7]),
  country("Trinidad and Tobago", "TT", "+1", 10),
  country("Tunisia", "TN", "+216", 8),
  country("Turkey", "TR", "+90", 10),
  country("Turkmenistan", "TM", "+993", 8),
  country("Tuvalu", "TV", "+688", [5, 6]),
  country("Uganda", "UG", "+256", 9),
  country("Ukraine", "UA", "+380", 9),
  country("United Arab Emirates", "AE", "+971", 9),
  country("Uruguay", "UY", "+598", 8),
  country("Uzbekistan", "UZ", "+998", 9),
  country("Vanuatu", "VU", "+678", 7),
  country("Venezuela", "VE", "+58", 10),
  country("Vietnam", "VN", "+84", 9),
  country("Yemen", "YE", "+967", 9),
  country("Zambia", "ZM", "+260", 9),
  country("Zimbabwe", "ZW", "+263", 9),
].sort((a, b) => a.name.localeCompare(b.name));

export function flagEmoji(iso2: string): string {
  return iso2
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)));
}

export function isValidNationalNumber(country: Country, digits: string): boolean {
  return country.lengths.includes(digits.length);
}

/** For UI hints, e.g. "Enter 10 digits" or "Enter 8-9 digits". */
export function lengthHint(country: Country): string {
  const { lengths } = country;
  if (lengths.length === 1) return `${lengths[0]} digits`;
  return `${Math.min(...lengths)}-${Math.max(...lengths)} digits`;
}
